name: MobHeads
main: com.cyber.mobheads.Main
version: ${project.version}
authors:
    - CyberDrain
    - Zombie_Striker
<<<<<<< Updated upstream
api-version: 1.13
=======
    - Marcoonline
api-version: 1.19
>>>>>>> Stashed changes
description: Allows players to behead mobs and other players!
commands:
    mobheads:
        description: Main command with several sub commands
        aliases: [mh, mobhead]
softdepend:
    - WorldGuard